function o = rgasp_optimoptions(solver, opt)
%RGASP_OPTIMOPTIONS  Optimization Toolbox options for the posterior mode search.
%
%   o = RGASP_OPTIMOPTIONS('fmincon', opt)
%   o = RGASP_OPTIMOPTIONS('fminunc', opt)
%
%   Built with OPTIMOPTIONS when it exists (MATLAB) and with OPTIMSET
%   otherwise, so the same call site works in both.  The objective supplies an
%   analytic gradient, and the Hessian is approximated with a limited-memory
%   BFGS update -- the same class of method the R package uses through
%   nloptr::lbfgs, but with the Optimization Toolbox's line search, scaling
%   and convergence tests.
%
%   opt fields consumed: maxEval, optimTolFun, optimTolX, verbose.

maxfev = max(200, 5*opt.maxEval);
maxit  = max(100, opt.maxEval);
if opt.verbose, disp_mode = 'iter'; else, disp_mode = 'off'; end

if rgasp_toolbox('optimoptions')
  % HessianApproximation / HessUpdate = 'lbfgs' needs a recent MATLAB; degrade
  % to the plain quasi-Newton defaults on older releases rather than erroring.
  try
    switch lower(solver)
        case 'fmincon'
            o = optimoptions('fmincon', ...
                'Algorithm',                  'interior-point', ...
                'SpecifyObjectiveGradient',   true, ...
                'HessianApproximation',       'lbfgs', ...
                'MaxFunctionEvaluations',     maxfev, ...
                'MaxIterations',              maxit, ...
                'OptimalityTolerance',        opt.optimTolFun, ...
                'StepTolerance',              opt.optimTolX, ...
                'Display',                    disp_mode);
        case 'fminunc'
            o = optimoptions('fminunc', ...
                'Algorithm',                  'quasi-newton', ...
                'SpecifyObjectiveGradient',   true, ...
                'HessUpdate',                 'lbfgs', ...
                'MaxFunctionEvaluations',     maxfev, ...
                'MaxIterations',              maxit, ...
                'OptimalityTolerance',        opt.optimTolFun, ...
                'StepTolerance',              opt.optimTolX, ...
                'Display',                    disp_mode);
        otherwise
            error('rgasp:optimizer', 'Unknown solver ''%s''.', solver);
    end
  catch err
    if strcmp(err.identifier, 'rgasp:optimizer'), rethrow(err); end
    o = optimoptions(lower(solver), ...
        'SpecifyObjectiveGradient',   true, ...
        'MaxFunctionEvaluations',     maxfev, ...
        'MaxIterations',              maxit, ...
        'Display',                    disp_mode);
  end
else
    % Legacy option struct (also accepted by MATLAB's solvers).
    o = optimset('GradObj', 'on', ...
                 'MaxFunEvals', maxfev, ...
                 'MaxIter',     maxit, ...
                 'TolFun',      opt.optimTolFun, ...
                 'TolX',        opt.optimTolX, ...
                 'Display',     disp_mode);
end
end
